version: '3'
services:
  a_osfinal:
    build:
      context: ./A_osfinal
      dockerfile: A_osfinal_Dockerfile
    depends_on:
      - kafka

  b_osfinal:
    build:
      context: ./B_osfinal
      dockerfile: B_osfinal_Dockerfile
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
